### ISSUE TITLE
Code does not compile on platforms other than Linux

### ISSUE THREAD

**Issue by hlubek** [ev3go/ev3dev#33]
I'm developing code on OS X and the package does not compile locally because of the unix.Poll dependency. This is generally not an issue because of cross compilation, but code completion and other local tools do not work correctly.

There should be a build tag for the code that uses the unix dependency in a separate file, so it has a bogus implementation for other platforms.

I got that working and will push a PR soon.

**Comment by kortschak** [comment]
Sorry about that; I have no access to platforms other than linux. Thanks for putting together a fix.

**Comment by kortschak** [comment]
Though I am curious about why you are compiling on macos, there is no sysfs modules for any of the systems the package is designed for.

**Comment by kortschak** [comment]
I am a little confused about this. The ev3dev package can only be useful on a linux system that is running an ev3dev kernel (or at least a kernel with ev3dev sysfs modules added).

It can be build for those systems on any system that supports Go by using the gc cross-compilation support. This would be something like:

```
GOOS=linux GOARCH=arm GOARM=5 go build <path>
```

Does this not work for you?

**Comment by hlubek** [comment]
Yes, I'm using it like that and it works like a charm ;)

My workflow is basically: edit and cross-compile locally (on OS X) and then copy the file to the EV3.

The issue at hand is more about `gocode` and other tools that do not work correctly with a package that does not compile.
