### ISSUE TITLE
ev3dev: cache invariant values for sensors

### ISSUE THREAD

**Issue by dlech** [ev3go/ev3dev#54]
Similar to #53, sensors have sysfs attributes that never change and could be cached.

`address`, `commands`, `driver_name`, `fw_version`, `modes`.

Additionally, some values only change when the mode changes. It is fairly safe to make the assumption that no one will change the mode outside of your program (but technically, not a 100% guarantee). These values could be cached when the mode is set.

`bin_data_format`, `decimals`, `mode`, `num_values`, `units`

**Comment by kortschak** [comment]
#62 caches `command`, `driver_name`, `fw_version` and `modes`. Other values are not guaranteed constant and so are not cached.
