### ISSUE TITLE
[question] Go seven times slower in retrieving sensor values than Python?

### ISSUE THREAD

**Issue by FlorianRaediker** [ev3go/ev3dev#93]
I recently tried Go on the EV3 because I hoped it would have better performance compared to Python.

In a while loop, the robot repeatedly retrieves a sensor value (in this case, from mindsensors.com Line Leader) and thus waits until it changes to a specific value.
I converted the corresponding Python code to Go, but I noticed Go is actually seven times slower in retrieving those sensor values. Below are the two test programs I wrote to compare the performance.

```python
ll = Sensor("in2")
ll.mode = "PID-ALL"
debug_print("Starting")
start = time.perf_counter()
for _ in range(1000):
    value = ll.value(2)
    if value == -1:
        # is on black line; the program would normally end the loop here
        pass
end = time.perf_counter()-start
debug_print(end)
```
Output (example): `0.9874834319999763`
```go
func main() {
    ll, err := ev3dev.SensorFor("ev3-ports:in2:i2c1", "ms-line-leader")
    if err != nil {
        log.Fatal(err)
    }
    ll.SetMode("PID-ALL")

    log.Println("Starting")
    start := time.Now()
    for i := 0; i < 1000; i++ {
        value, err := ll.Value(2)
        if err != nil {
            log.Fatal(err)
        }
        if value == "-1" {
            // is on black line
        }
    }
    end := time.Since(start)
    log.Println(end)
}
```
Output (example): `6.850100872s`

While Python takes about 1 second on my EV3 for the loop, Go takes about 7 seconds.

The question I'm asking myself is: Am I doing something wrong here? Because I usually would expect Go to be faster, and indeed the startup time is much lower.
If not: Why is Go seven times slower? I couldn't find any major difference between how the python `ev3dev2` module and the Go `github.com/ev3go/ev3dev` package retrieve sensor values.

PS: I think ~143 checks per second with Go are more than enough, but I'm opening this issue because I'm curious to find out what causes  this. As you might have guessed, I've got little to no experience with Go.

**Comment by dlech** [comment]
>  I couldn't find any major difference between how the python `ev3dev2` module and the Go `github.com/ev3go/ev3dev` package retrieve sensor values.

I think this major difference is that ev3go opens, reads and closes the file on each read whereas ev3dev-lang-python leaves the file open and only seeks and reads to get the value.

**Comment by kortschak** [comment]
>I think this major difference is that ev3go opens, reads and closes the file on each read whereas ev3dev-lang-python leaves the file open and only seeks and reads to get the value.

This is something that ev3go could do if it's seen to be worth it. To d this I'd keep a registry of files (`map[string]*os.File`) and reuse opened files. It's not clear to me how important it is though.

**Comment by FlorianRaediker** [comment]
Thanks to both of you for your helpful comments.

> To d this I'd keep a registry of files (`map[string]*os.File`) and reuse opened files.

I wanted to learn a bit of Go and tried to implement such a registry.
It worked and the above snippet now takes around 1.5-2 seconds, so it's still a bit slower than Python I guess, but it's definitely an improvement, so I'll open a PR (hope that's ok).

**Comment by kortschak** [comment]
@dlech, is `readat` usable with sysfs files in a sensible way? Either if we have a small known maximum file size or multiple readat calls on a file are meaningful (intuitively this latter seems less likely).

**Comment by dlech** [comment]
Probably. Technically, sysfs files have a fixed size of 4096 bytes on the EV3 (memory page size). But a much smaller number could be used. The longest attribute values are probably `modes`. 128 bytes is probably sufficient.
