### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by s4m-mo** [ev3go/ev3dev#96]
I have encountered an install issue that has raised this error

```
go get -v github.com/ev3go/ev3dev
github.com/ev3go/ev3dev
# github.com/ev3go/ev3dev
C:\Users\<USERNAME>\go\pkg\mod\github.com\ev3go\ev3dev@v0.0.0-20210313113244-a5fda5c6a492\evdev.go:39:32: not enough arguments in call to syscall.Syscall
C:\Users\<USERNAME>\go\pkg\mod\github.com\ev3go\ev3dev@v0.0.0-20210313113244-a5fda5c6a492\evdev.go:39:33: undefined: syscall.SYS_IOCTL
C:\Users\<USERNAME>\go\pkg\mod\github.com\ev3go\ev3dev@v0.0.0-20210313113244-a5fda5c6a492\lcd.go:79:17: undefined: syscall.Mmap
C:\Users\<USERNAME>\go\pkg\mod\github.com\ev3go\ev3dev@v0.0.0-20210313113244-a5fda5c6a492\lcd.go:79:62: undefined: syscall.PROT_READ
C:\Users\<USERNAME>\go\pkg\mod\github.com\ev3go\ev3dev@v0.0.0-20210313113244-a5fda5c6a492\lcd.go:79:80: undefined: syscall.PROT_WRITE
C:\Users\<USERNAME>\go\pkg\mod\github.com\ev3go\ev3dev@v0.0.0-20210313113244-a5fda5c6a492\lcd.go:79:100: undefined: syscall.MAP_SHARED
C:\Users\<USERNAME>\go\pkg\mod\github.com\ev3go\ev3dev@v0.0.0-20210313113244-a5fda5c6a492\lcd.go:103:9: undefined: syscall.Munmap
```

**Comment by kortschak** [comment]
The ev3go libraries target linux devices running the ev3dev linux distribution, they make use of linux-specific features and so will not compile for a windows (or macos) host which is what you have tried to do. Fortunately, Go provides the capacity to cross compile for other architectures and OS hosts easily (or you can compile on the ev3dev device if you are patient). The instructions for this are given in the [README](https://github.com/ev3go/ev3dev#quick-start-compiling-for-a-brick). You do not need to use go get, just a git clone is enough to get the source onto your windows machine (although you can use go get if you prefix it with the env vars to specify a linux armv5 host, `GOOS=linux GOARCH=arm GOARM=5`).
